name: daily-quotes # snap application name
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Get notified with motivational quotes! # 79 char long summary
description: |
  Get notified with nice motivational quotes every time you get on your screen! :)

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  daily-quote:
    autostart: daily-quotes.desktop
    command: bin/daily-quote
    plugs:
      - x11
      - process-control
      - desktop
      - desktop-legacy
      - network-bind
      - home

parts:
  daily-quote:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    organize:
      daily-quote.bash: bin/daily-quote
    stage-packages:
      - curl
      - jq
      - notify-osd
      - libnotify-bin

  desktop-file:
    plugin: dump
    source: desktop-file/
